name: portfolio_app
description: A Flutter application for your portfolio.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.4.0
  flutter_form_builder: ^7.0.0
  cached_network_image: ^3.2.0
  path_provider: ^2.0.2
  json_serializable: ^6.0.1
  url_launcher: ^6.0.9  # Add url_launcher dependency
  font_awesome_flutter: ^10.0.0  # Add font_awesome_flutter dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/profile.png # Make sure this matches the folder where your images are

